name: Update README with Random GIF

on:
  schedule:
    - cron: "* * * * *" # Runs every minute
  workflow_dispatch: # Allows manual trigger if needed.

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run the updateReadme script
        run: node updateReadme.js

      - name: Commit and push changes
        run: |
          git config --global user.name "Sanni-Damilola"
          git config --global user.email "sannifortune11@gmail.com"
          git add README.md
          git commit -m "Update GIF section in README with a new random GIF"
          git push
